Repository ezsystems/ezplatform-matrix-fieldtype, pull requests merged in 2020-01, with the labels that each got.

#23 EZP-31271: Simplified access to field settings in the ezmatrix_field twig block
  src/bundle/Resources/views/themes/admin/matrix_fieldtype/content_fields.html.twig
  src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig
Labels: Bug, QA approved

#27 Translation configuration name has been unified
  src/bundle/DependencyInjection/EzPlatformMatrixFieldtypeExtension.php
Labels: Improvement

#28 Add basic Travis setup
  .php_cs
  .travis.yml
  composer.json
  src/lib/GraphQL/FieldValueResolver.php
  src/lib/GraphQL/InputHandler.php
  src/lib/GraphQL/Schema/MatrixFieldDefinitionInputSchemaWorker.php
  src/lib/GraphQL/SilentRow.php
Labels: Ready for review

#25 EZP-31264: Implemented Indexable for ezmatrix FT
  .gitignore
  .php_cs
  .travis.yml
  composer.json
  phpunit-integration-legacy.xml
  src/bundle/Resources/config/services/fieldtype.yml
  src/lib/FieldType/Indexable.php
  src/lib/FieldType/Type.php
  tests/integration/API/Repository/SearchServiceTest.php
  tests/integration/CoreSetupFactoryTrait.php
  tests/integration/LegacySetupFactory.php
Labels: Improvement, QA approved

#29 EZP-31278: Removed usage of the obsolete RegisterLimitationTypePass
  tests/integration/CoreSetupFactoryTrait.php
Labels: Improvement

#26 EZP-31265 - Add support for attr.class
  src/bundle/Resources/views/themes/standard/matrix_fieldtype/content_fields.html.twig
Labels: Improvement, QA approved

#31 EZP-31342: Added argument to service, to use valid database connection
  src/bundle/Resources/config/services/migration.yml
Labels: Bug, QA approved
